baseURL = "https://test-new-template.github.io/"
title = "SASIP"
theme = "hugo-advance"
paginate = 3
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
    google_analytics_id = ""
    enable_dark_mode = false
    enable_nested_menu = true # allows dropdown menus in main menu
    enable_fixed_header = true # if true the header will be sticky and animate on scroll
    enable_language_switcher = false

    [params.colors]
        [params.colors.light]
            base = "#ffffff"
            base_offset = "#f2f2f2"
            base_text = "#202020"
            base_text_offset = "#625c5c"
            alt = "#f4f5fb"
            alt_offset = "#CCCCCC"
            alt_text = "#202020"
            alt_text_offset = "#625c5c"
            primary = "#2b3af7"
            primary_offset = "#702bf7"
            primary_text = "#ffffff"
            primary_text_offset = "#79bcff"
        [params.colors.dark]
            base = "#121212"
            base_offset = "#1e1e1e"
            base_text = "#ffffff"
            base_text_offset = "#d7d7d7"
            alt = "#1e1e1e"
            alt_offset = "#2f2f2f"
            alt_text = "#fafafa"
            alt_text_offset = "#a8a4a4"
            primary = "#2b5df7"
            primary_offset = "#a62bf7"
            primary_text = "#eeebfc"
            primary_text_offset = "#a7a7a7"

    [params.fonts]
        google_fonts = "https://fonts.googleapis.com/css2?family=Fira+Mono&family=Lato:wght@300;400;700&family=Source+Sans+Pro&display=swap"
        heading = "Lato"
        base = "Source Sans Pro"
        monospace = "Fira Mono"

    [params.logo]
        logo = "images/ice-logo.jpg" # Desktop logo
        logo_mobile = "images/ice-logo.jpg" # Mobile logo, typically the smaller square version of your logo (logomark)
        logo_invert = "images/ice-logo.jpg" # Desktop logo in white, for use when the header is transparent
        logo_invert_mobile = "images/ice-logo.jpg" # Mobile logo in white

    [params.seo]
        meta_twitter_site = "@zerostaticio"
        meta_twitter_creator = "@zerostaticio"

    [params.footer]
        show_site_title = true
        show_copyright = true
        show_social_media_links = true
        show_languages = false
        enable_menu_footer_primary = false
        footer_primary_menu_title = "Product"
        enable_menu_footer_secondary = false
        footer_secondary_menu_title = "Company"
        enable_menu_footer_tertiary = false
        footer_tertiary_menu_title = "Support"



[languages]
    [languages.en]
        weight = 0
        languageName = "English"
        contentDir = "content/en"
    [languages.fr]
        weight = 1
        languageName = "Français"
        contentDir = "content/fr"
        title = "Hugo Avance"
        [languages.fr.params.footer]
            show_site_title = true
            show_copyright = true
            show_social_media_links = true
            show_languages = true
            enable_menu_footer_primary = true
            footer_primary_menu_title = "Produit"
            enable_menu_footer_secondary = true
            footer_secondary_menu_title = "Compagnie"
            enable_menu_footer_tertiary = true
            footer_tertiary_menu_title = "Support"
        [languages.fr.menu]
            [[languages.fr.menu.main]]
                name = "Acheter"
                url = "https://www.zerostatic.io/theme/hugo-advance/"
                weight = 10
            [[languages.fr.menu.footer_tertiary]]
                name = "Acheter"
                url = "https://www.zerostatic.io/theme/hugo-advance/"
                weight = 10

[permalinks]
    posts = "blog/:year/:month/:title/"
    pages = ":slug/"

[taxonomies]
    tag = "tags"
    category = "categories"
    portfolio =  "portfolio"
    author = "authors"
